# android
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
# org.gradle.java.home=C\:\\Users\\84384\\.jdks\\jdk21\\jdk21.0.12_8

#alternate band-aid for the `jvm target compatibility should be set to the same Java version` problem:
kotlin.jvm.target.validation.mode = IGNORE
